Repository freeCodeCamp/mobile, pull requests merged in 2022-01, with the labels that each got.

#127 fix: null error on forum
  mobile-app/lib/ui/views/forum/forum-html-handler/forum_html_handler.dart
Labels: status: waiting review, scope: logic

#112 feat: message not logged in users to login to comment on a topic
  mobile-app/lib/ui/views/forum/forum-categories/forum_category_view.dart
  mobile-app/lib/ui/views/forum/forum-login/forum_login_view.dart
  mobile-app/lib/ui/views/forum/forum-login/forum_login_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-post/forum_post_view.dart
  mobile-app/lib/ui/views/forum/forum-post/forum_post_viewmodel.dart
  mobile-app/lib/ui/widgets/setup_dialog_ui.dart
Labels: scope: ui, status: waiting review, scope: logic

#153 feat: link to read articles online if app fails to fetch articles
  mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
Labels: scope: ui, status: waiting review, Next Release

#156 feat: syntax view for news
  mobile-app/lib/ui/views/news/html_handler/html_handler.dart
Labels: scope: ui, status: waiting review, Next Release

#157 fix: open learn externally for now
  mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
Labels: status: waiting review, scope: logic, Next Release

#169 feat: better news tags
  mobile-app/lib/app/app.router.dart
  mobile-app/lib/models/article_model.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart
  mobile-app/lib/ui/widgets/tag_widget.dart
  mobile-app/pubspec.lock
Labels: scope: ui, status: waiting review, scope: logic

#152 fix: put models in separate folders
  mobile-app/lib/app/app.router.dart
  mobile-app/lib/models/forum/forum_category_model.dart
  mobile-app/lib/models/forum/forum_post_model.dart
  mobile-app/lib/models/forum/forum_search_model.dart
  mobile-app/lib/models/forum/forum_user_model.dart
  mobile-app/lib/models/news/article_model.dart
  mobile-app/lib/models/news/bookmarked_article_model.dart
  mobile-app/lib/ui/views/forum/forum-categories/forum_category_builder.dart
  mobile-app/lib/ui/views/forum/forum-categories/forum_category_view.dart
  mobile-app/lib/ui/views/forum/forum-categories/forum_category_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-comment/forum_comment_view.dart
  mobile-app/lib/ui/views/forum/forum-create-post/forum_create_post_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-html-handler/forum_html_handler.dart
  mobile-app/lib/ui/views/forum/forum-post-feed/forum_post_feed_view.dart
  mobile-app/lib/ui/views/forum/forum-post-feed/forum_post_feed_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-post/forum_post_view.dart
  mobile-app/lib/ui/views/forum/forum-post/forum_post_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-search/forum_search_view.dart
  mobile-app/lib/ui/views/forum/forum-search/forum_search_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-user-profile/forum_user_profile_view.dart
  mobile-app/lib/ui/views/forum/forum-user-profile/forum_user_profile_viewmodel.dart
  mobile-app/lib/ui/views/forum/forum-user/forum_user_view.dart
  mobile-app/lib/ui/views/forum/forum-user/forum_user_viewmodel.dart
  mobile-app/lib/ui/views/news/news-article-post/news_article_post_header.dart
  mobile-app/lib/ui/views/news/news-article-post/news_article_post_view.dart
  mobile-app/lib/ui/views/news/news-article-post/news_article_post_viewmodel.dart
  mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_view.dart
  mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_viewmodel.dart
  mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_widget.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart
  mobile-app/lib/ui/widgets/text_function_bar_widget.dart
Labels: status: merge conflict

#158 fix: dry out drawer widget
  mobile-app/lib/ui/widgets/drawer_widget/drawer_button.dart
  mobile-app/lib/ui/widgets/drawer_widget/drawer_web_buttton.dart
  mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
  mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
Labels: scope: ui, status: waiting review

#170 feat: news author update and news feed drying
  mobile-app/lib/app/app.dart
  mobile-app/lib/app/app.router.dart
  mobile-app/lib/models/news/article_model.dart
  mobile-app/lib/ui/views/news/news-author/news_author_view.dart
  mobile-app/lib/ui/views/news/news-author/news_author_viewmodel.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart
  mobile-app/lib/ui/widgets/article_list_widget.dart
Labels: status: waiting review

#151 fix: cursor position after using markdown formatting
  mobile-app/lib/ui/theme/fcc_theme.dart
  mobile-app/lib/ui/views/forum/forum-comment/forum_comment_view.dart
  mobile-app/lib/ui/views/forum/forum-post/forum_post_view.dart
  mobile-app/lib/ui/widgets/text_function_bar_widget.dart
Labels: scope: ui, status: waiting review
