Repository freeCodeCamp/mobile, pull requests merged in 2022-07, with the labels that each got.

#436 fix: learn superblocks for new API version
  mobile-app/lib/ui/views/learn/learn_viewmodel.dart
  mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
Labels: status: waiting review

#435 fix: progressbar minimun width
  mobile-app/lib/ui/widgets/podcast_widgets/podcast_progressbar_widget.dart
Labels: scope: ui, status: waiting review, Next Release

#447 fix: coderadio pause/play button alignment
  mobile-app/lib/ui/views/code_radio/code_radio_view.dart
Labels: scope: ui, status: waiting review, Next Release

#429 feat: one audio service handler
  mobile-app/analysis_options.yaml
  mobile-app/assets/sql/4_delete_all_values.sql
  mobile-app/lib/app/app.dart
  mobile-app/lib/app/app.locator.dart
  mobile-app/lib/main.dart
  mobile-app/lib/service/audio_service.dart
  mobile-app/lib/service/code_radio_service.dart
  mobile-app/lib/service/episode_audio_service.dart
  mobile-app/lib/service/podcasts_service.dart
  mobile-app/lib/ui/views/code_radio/code_radio_viemodel.dart
  mobile-app/lib/ui/views/code_radio/code_radio_view.dart
  mobile-app/lib/ui/views/podcast/episode-list/episode_list_viewmodel.dart
  mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart
  mobile-app/lib/ui/widgets/podcast_widgets/podcast_progressbar_widget.dart
  mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart
  mobile-app/pubspec.lock
  mobile-app/pubspec.yaml
Labels: status: waiting review

#470 fix: pane ui
  mobile-app/assets/fonts/Inter-Bold.ttf
  mobile-app/assets/fonts/Inter-Regular.ttf
  mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart
  mobile-app/lib/ui/views/learn/widgets/description/description_widget_view.dart
  mobile-app/lib/ui/views/learn/widgets/hint/hint_widget_view.dart
  mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_view.dart
  mobile-app/pubspec.yaml
Labels: status: waiting update, status: merge conflict
