Repository freeCodeCamp/mobile, pull requests merged in 2025-04, with the labels that each got.

#1379 fix: rename NewsApiServive to NewsApiService
  mobile-app/lib/app/app.dart
  mobile-app/lib/app/app.locator.dart
  mobile-app/lib/main.dart
  mobile-app/lib/service/news/api_service.dart
  mobile-app/lib/ui/views/news/news-author/news_author_viewmodel.dart
  mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart
  mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart
  mobile-app/lib/ui/widgets/tutorial_list_widget.dart
Labels: status: waiting update

#1372 refactor: replace 'Inter' and 'RobotoMono' fonts with 'Hack' and 'Lato'
  mobile-app/assets/fonts/Hack-Regular.ttf
  mobile-app/assets/fonts/Inter-Bold.ttf
  mobile-app/assets/fonts/Inter-Regular.ttf
  mobile-app/assets/fonts/RobotoMono-Bold.ttf
  mobile-app/assets/fonts/RobotoMono-Regular.ttf
  mobile-app/lib/ui/theme/fcc_theme.dart
  mobile-app/lib/ui/views/auth/privacy_view.dart
  mobile-app/lib/ui/views/learn/block/block_view.dart
  mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
  mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
  mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
  mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_view.dart
  mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
  mobile-app/lib/ui/views/learn/landing/landing_view.dart
  mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/description/description_widget_view.dart
  mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart
  mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
  mobile-app/lib/ui/views/news/html_handler/html_handler.dart
  mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_view.dart
  mobile-app/lib/ui/views/podcast/episode-list/episode_list_view.dart
  mobile-app/lib/ui/views/settings/delete-account/delete_account_view.dart
  mobile-app/lib/ui/widgets/podcast_widgets/podcast_title_widget.dart
  mobile-app/pubspec.yaml
Labels: status: merge conflict

#1407 fix: link text color
  mobile-app/lib/ui/views/news/html_handler/html_handler.dart
Labels: status: waiting review
